import "../../app/globals.css";
// import Footer from "./components/Footer.js";
// import Header from "./components/Header";
// import bgImgs from "../../public/images/image.jpg";
import Footer from '../../components/Footer'
import Header from '../../components/Header'
export const metadata = {
  title: {
    absolute: "Bharat Floorings & tiles",
    default: "Bharat Floorings & tiles",
    template: "%s | Bharat Floorings & tiles",
  },
  description: "Generated by Next.js",
};

export default function Layout({ children, backgroundImage }) {
  return (
    <html lang="en">
      <body>
        <Header bgImg={backgroundImage} title="Press releases" />
        <main className=" max-w-[1920px] mx-auto">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
