import "./globals.css";
import Footer from "./components/Footer.js";
import Header from "./components/Header";
import bgImgs from "../../public/images/image.jpg";
export const metadata = {
  title: {
    absolute: "Bharat Floorings & tiles",
    default: "Bharat Floorings & tiles",
    template: "%s | Bharat Floorings & tiles",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children, backgroundImage }) {
  return (
    <html lang="en">
      <body>
        <Header bgImg={bgImgs} title="Press releases" />
        <main className=" max-w-[1920px] mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
